config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :restaurants, only: %i[index show new create destroy] do
    resources :reviews, only: %i[new create]
  end
  resources :reviews, only: %i[destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, :address, :phone_number, :category, presence: true
  validates :category, inclusion: { in: %w[chinese italian japanese french belgian], message: '%<value> is not a valid categoty' }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, :rating, presence: true
  validates :rating, numericality: { only_integer: true, in: 0..5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: [:new, :create]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@review.restaurant), status: :see_other
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/restaurants/">
      <img src="../../assets/icon.png" alt="" width="30" height="24" class="d-inline-block align-text-top">
      RestaurantApp
    </a>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/restaurants/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/restaurants/new">Add Restaurant</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <div class="row justify-content-start">
    <% @restaurants.each do | restaurant | %>
      <div class="col-3 mt-5">
        <div class="card" style="width: 18rem;">
          <img src="https://source.unsplash.com/random/1600x900/?restaurant" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title"><%= restaurant.name %></h5>
            <p class="card-text"><%= "Address: #{restaurant.address} || Phone: #{restaurant.phone_number} || Category: #{restaurant.category}" %></p>
            <%= link_to "Aditional infos.", restaurant_path(restaurant), class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>



<%#
2 - como usar o unsplash pra escolher dentro de uma seleção esp

4 - como fazer o path pra imagem do logo
%>

app/views/restaurants/new.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/restaurants/">
      <img src="../../assets/icon.png" alt="" width="30" height="24" class="d-inline-block align-text-top">
      RestaurantApp
    </a>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/restaurants/">Home</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <%= simple_form_for @restaurant do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.input :category %>
    <%= f.submit "Create restaurant", class: "btn btn-primary" %>
  <% end %>
  <%= link_to "Cancel", restaurants_path %>
</div>

app/views/restaurants/show.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/restaurants/">
      <img src="../../assets/icon.png" alt="" width="30" height="24" class="d-inline-block align-text-top">
      RestaurantApp
    </a>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/restaurants/">Home</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

<h1><%= @restaurant.name %></h1>
<p><%= "#{@restaurant.category}" || "#{@restaurant.address}" || "#{@restaurant.phone_number}" %></p>

<% @restaurant.reviews.each do | review | %>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">
      <%= "#{review.content} || #{review.rating}" %>
      <%= link_to "delete", review_path(review), data: {turbo_method: :delete, turbo_confirm: "Are you shure?"} %>
    </li>
  </ul>
<% end %>

<%= link_to "Add review", new_restaurant_review_path(@restaurant) %>
<%= link_to "back", restaurants_path %>

app/views/reviews/new.html.erb
<div class="container">
  <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :content %>
    <%= f.input :rating %>
    <%= f.submit "Submit review", class: "btn btn-primary" %>
  <% end %>
  <%= link_to "Cancel", restaurants_path %>
</div>